accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/accounts_update/", views.accounts_update, name="accounts_update"),
    path("password_update/", views.password_update, name="password_update"),
    path("<int:pk>/", views.detail, name="detail"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:pk>", views.detail, name="detail"),
    path("<int:article_pk>/comments", views.comments, name="comments"),
    path(
        "<int:article_pk>/comments_delete/<int:pk>",
        views.comments_delete,
        name="comments_delete",
    ),
    path("error", views.error, name="error"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('review/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    gender_choice = (
        ("Male", "Male"),
        ("Female", "Female"),
    )

    genre_choice = (
        ("Action", "Action"),
        ("Comedy", "Comedy"),
        ("Drama", "Drama"),
        ("Fantasy", "Fantasy"),
        ("Horror", "Horror"),
        ("Mystery", "Mystery"),
        ("Romance", "Romance"),
        ("Thriller", "Thriller"),
        ("Sci-fi", "Sci-fi"),
        ("Others", "Others"),
    )

    gender = models.CharField(max_length=8, choices=gender_choice)
    genre = models.CharField(max_length=20, choices=genre_choice)
    image = models.ImageField(upload_to="images/profile", blank=True)
    pass

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm


class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
            "gender",
            "genre",
            "image",
        )


class UserCustomChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
            "gender",
            "genre",
            "image",
        )


class UserCustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        pass

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from articles.models import Review
from .forms import (
    UserCustomCreationForm,
    UserCustomChangeForm,
    UserCustomPasswordChangeForm,
)


# 회원가입
def signup(request):
    if request.method == "POST":
        form = UserCustomCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("articles:index")
    else:
        form = UserCustomCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


# 로그인
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


# 로그아웃
@login_required
def logout(request):
    auth_logout(request)
    return redirect("articles:index")


# 회원수정
@login_required
def accounts_update(request, pk):
    user = get_user_model().objects.get(pk=pk)
    if user == request.user:
        if request.method == "POST":
            form = UserCustomChangeForm(
                request.POST, request.FILES, instance=request.user
            )
            if form.is_valid():
                form.save()
                return redirect("accounts:detail", request.user.pk)
        else:
            form = UserCustomChangeForm(instance=request.user)
        context = {
            "form": form,
        }
        return render(request, "accounts/accounts_update.html", context)
    else:
        return redirect("articles:error")


# 비번수정
@login_required
def password_update(request):
    if request.method == "POST":
        form = UserCustomPasswordChangeForm(request.POST, request.user)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:detail", request.user.pk)
    else:
        form = UserCustomPasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password_update.html", context)


# 프로필
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    review = user.review_set.all()
    context = {
        "user": user,
        "review": review,
    }
    return render(request, "accounts/detail.html", context)

accounts/templates/accounts/accounts_update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}회원정보 수정{% endblock title %}
{% block css %}{% endblock css %}

{% block content %}
<div class="container my-3">
  <h1 class="text-center">회원정보 수정</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a class="btn btn-primary" href="{% url 'accounts:detail' request.user.pk %}" role="button">뒤로가기</a>
    <button class="btn btn-success" type="submit">수정하기</button>
  </form>
  <a class="btn btn-primary my-2" href="{% url 'accounts:password_update' %}" role="button">비밀번호 수정하기</a>
</div>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="my-3 d-flex flex-column">
    <div class="mb-3 d-flex justify-content-center">
      {% if user.image %}
      <img src="{{ user.image.url }}" width="200" height="180" class="rounded-circle">
      {% else %}
      <img width="200" height="180" class="rounded-circle" src="https://mblogthumb-phinf.pstatic.net/MjAyMDExMDFfMTA1/MDAxNjA0MjI4ODc1Mzk0.05ODadJdsa3Std55y7vd2Vm8kxU1qScjh5-3eVJ9T-4g.h7lHansSdReVq7IggiFAc44t2W_ZPTPoZWihfRMB_TYg.JPEG.gambasg/%EC%9C%A0%ED%8A%9C%EB%B8%8C_%EA%B8%B0%EB%B3%B8%ED%94%84%EB%A1%9C%ED%95%84_%ED%8C%8C%EB%9E%91.jpg?type=w800">
      {% endif %}
    </div>
    <div class="d-flex justify-content-center">
      <h1>{{ user.username }}님의 프로필</h1>
    </div>
  </div>
  
  <div class="mb-3 row">
    <label for="staticEmail" class="col-sm-2 col-form-label badge text-bg-secondary mt-2 pt-2">Email</label>
    <div class="col-sm-10">
      <input readonly class="form-control-plaintext" value="{{ user.email }}">
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label badge text-bg-secondary mt-2 pt-2">성별</label>
    <div class="col-sm-10">
      <p class="form-control-plaintext">{{ user.gender }}</p>
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label badge text-bg-secondary mt-2 pt-2">장르</label>
    <div class="col-sm-10">
      <p class="form-control-plaintext">{{ user.genre }}</p>
    </div>
  </div>

  <div class="mb-3 d-flex justify-content-center">
    {% if request.user.pk == user.pk %}
    <a class="mb-3 me-2 btn btn-danger" href="{% url "accounts:accounts_update" request.user.pk %}" role="button">수정하기</a>
    {% endif %}
    <a class="mb-3 btn btn-primary" href="{% url "articles:index" %}" role="button">뒤로가기</a>
  </div>

  <div>
    <h2 class="d-flex justify-content-center">작성한 게시글</h2>
    {% for article in review %}
    <div class ="mb-3 row">
      <label class="col-sm-2 col-form-label badge text-bg-secondary mt-2 pt-4">{{ article.pk }}번 글</label>
      <div class="col-sm-10">
        <span class="form-control-plaintext">제목 : {{ article.title }}</span>
        <span class="form-control-plaintext">내용 : {{ article.content }}</span>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}로그인{% endblock title %}
{% block css %}{% endblock css %}

{% block content %}
<div class="container my-3">
  <h1 class="text-center">로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">회원가입</a>
    <button class="btn btn-success" type="submit">로그인</button>
    <a class="btn btn-primary" href="{% url 'articles:index' %}" role="button">뒤로가기</a>
  </form>
  
</div>
{% endblock content %}

accounts/templates/accounts/password_update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}비밀번호 수정{% endblock title %}
{% block css %}{% endblock css %}

{% block content %}
<div class="container">
  <h1 class="text-center">비밀번호 수정</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a class="btn btn-primary" href="{% url 'accounts:accounts_update' request.user.pk %}" role="button">뒤로가기</a>
    <button class="btn btn-success" type="submit">수정하기</button>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container my-3">  
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">OK</button>
  </form>
</div>

{% endblock content %}