accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/accounts_update/", views.accounts_update, name="accounts_update"),
    path("password_update/", views.password_update, name="password_update"),
    path("<int:pk>/", views.detail, name="detail"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:pk>", views.detail, name="detail"),
    path("<int:article_pk>/comments", views.comments, name="comments"),
    path(
        "<int:article_pk>/comments_delete/<int:pk>",
        views.comments_delete,
        name="comments_delete",
    ),
    path("error", views.error, name="error"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('review/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


# Create your models here.
class Review(models.Model):
  genre_choice = (
    ('Action', 'Action'),
    ('Comedy', 'Comedy'),
    ('Drama', 'Drama'),
    ('Fantasy', 'Fantasy'),
    ('Horror', 'Horror'),
    ('Mystery', 'Mystery'),
    ('Romance', 'Romance'),
    ('Thriller', 'Thriller'),
    ('Sci-fi', 'Sci-fi'),
    ('Others', 'Others'),
  )
  rating_choice = (
    ('1', '⭐'),
    ('2', '⭐⭐'),
    ('3', '⭐⭐⭐'),
    ('4', '⭐⭐⭐⭐'),
    ('5', '⭐⭐⭐⭐⭐'),
  )

  title = models.CharField(max_length=50)
  content = models.TextField()
  movie_name = models.CharField(max_length=50)
  grade = models.CharField(max_length=50, choices=rating_choice)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  genre = models.CharField(max_length=50, choices=genre_choice)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='images/movies', blank=True)
  image_thumbnail = ImageSpecField(source='image',
                                processors=[ResizeToFill(295, 295)],
                                format='JPEG',
                                options={'quality': 80})

class Comment(models.Model):
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  review = models.ForeignKey(Review, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from django import forms
from .models import Review, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title','content','movie_name','grade','genre','image',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

articles/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    articles = Review.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.user = request.user
            temp.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/forms.html', context)

@login_required
def update(request, pk):
    article = Review.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:index')
        else:
            form = ArticleForm(instance=article)
        context = {
            'form': form
        }
        return render(request, 'articles/forms.html', context)
    else:
        return redirect('articles:error')

@login_required
def delete(request, pk):
    article = Review.objects.get(pk=pk)
    if request.user.pk == article.user.pk:
        Review.objects.get(pk=pk).delete()
        return redirect('articles:index')
    else:
        return redirect('articles:error')

@login_required
def detail(request, pk):
    article = Review.objects.get(pk=pk)
    form = CommentForm()
    context = {
        'form': form,
        'article': article
    }
    return render(request, 'articles/detail.html', context)

@login_required
def comments(request, article_pk):
    article = Review.objects.get(pk=article_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.review = article
            temp.user = request.user
            temp.save()
            return redirect('articles:detail', article.pk)

@login_required
def comments_delete(request, article_pk, pk):
    comment = Comment.objects.get(pk=pk)
    if comment.user == request.user:
        comment.delete()
        return redirect('articles:detail', article_pk)
    else:
        return redirect('articles:error')

def error(request):
    return render(request, 'articles/error.html')

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% load crispy_forms_tags %}  

{% block title %}{{ article.title }}{% endblock title %}

{% block css %}<link rel="stylesheet" href="{% static 'css/style.css' %}">{% endblock css %}


{% block content %}
<section class="review-main container my-5">
    <h1 class='text-center fw-bold mb-4'>{{ article.title }}</h1>
    <div class='review-main-info d-flex justify-content-center align-items-center'>
        {% if article.image_thumbnail %}
        <img class="reviewimage" src="{{ article.image.url }}" alt="없음">
        {% else %}
        <img class="reviewimage" src="https://dummyimage.com/295x295/000/fff" alt="">
        {% endif %}
        <div class="ms-4 informations">
            <div class='d-flex mb-3 align-items-end'>
                <h3 class="mb-0 fw-bold">{{ article.movie_name }}</h3>
                <h5 class="ms-3 mb-0 text-muted">| {{ article.genre }}</h5>
            </div>
            <hr>
            <h4>{{ article.get_grade_display }}</h4>
            <div class="review-user d-flex align-items-center">
                <img class='review-user-img me-3' src="{{ article.user.image.url }}" alt="">
                <h5>Written by: {{ article.user.username }}</h5>
            </div>
            <p class='mt-3 text-muted'>{{ article.created_at }} | {{ article.updated_at }}</p>
            <a class="btn btn-outline-secondary me-3 btn-sm" href="{% url 'articles:index' %}" role="button">뒤로가기</a>
            {% if request.user == article.user %}
            <a class="btn btn-outline-danger me-3 btn-sm" href="{% url 'articles:update' article.pk %}" role="button">수정하기</a>
            <a class="btn btn-outline-danger btn-sm" href="{% url 'articles:delete' article.pk %}" role="button">삭제하기</a>
            {% endif %}
        </div>
    </div>
</section>

<section class='review-content container'>
    <h2>리뷰</h2>
    <h4>{{ article.content }}</h4>
</section>

<section class="comments container my-5">
    <h4> 댓글 </h4>

    <button class="btn btn-primary my-3 btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        글 쓰기
    </button>

    <div class="collapse" id="collapseExample">
    <div class="card card-body">
        <form action="{% url 'articles:comments' article.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">OK</button>
        </form>
    </div>
    </div>

    <div class="all-comments">
        {% for comment in article.comment_set.all %}
        <div class="comment my-3">
            <div class="comment-user d-flex align-items-center">
                <img class="comment-image" src="{{ comment.user.image.url }}" alt="" srcset="{{ comment.user.img }}">
                <div class="comment-user-info">
                    <h6 class='mb-0 fw-bold'>{{ comment.user }}</h6>
                    <h6 class='mb-0'>{{ comment.created_at }}</h6>
                </div>
            </div>
            <h5>{{ comment.content }}</h5>
            <a class="btn btn-outline-danger btn-sm" href="{% url 'articles:comments_delete' article.pk comment.pk %}" role="button">삭제</a>
        </div> 
        {% endfor %}
    </div>
</section>

{% endblock content %}

articles/templates/articles/error.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
 잘못된 요청입니다.
 <a class="btn btn-primary" href="{% url 'articles:index' %}">메인으로</a>
{% endblock %}

articles/templates/articles/forms.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container my-3">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">OK</button>
        <a href="{% url 'articles:index' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-3">
    <a href="{% url 'articles:create' %}" class="btn btn-primary">글 작성</a><br>
    
    <div class="row row-cols-lg-4 row-cols-xs-2 mb-3">
        {% for article in articles %}
        <div class="col mt-3">
            <div class="card shadow">
                {% if article.image_thumbnail %}
                <img class="card-top-img" src="{{ article.image_thumbnail.url }}" alt="없음">
                {% else %}
                <img class="card-top-img" src="https://dummyimage.com/295x295/000/fff" alt="">
                {% endif %}
                <div class="card-body p-2">
                    <a class="card-title" style="text-decoration:none; color:black" href="{% url 'articles:detail' article.pk %}"><h5>{{ article.title }}</h5></a>
                    <a style="text-decoration:none; color:black" href="{%url 'accounts:detail' article.user.pk %}">작성자:{{ article.user.username }}</a>
                    <p class="text-muted">{{ article.created_at.date }}</p>
                </div>
            </div>
        </div>
        {% endfor %}        
    </div>
</div>
{% endblock %}